name: Build Rust static binary (musl)
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y musl-tools clang llvm-dev libclang-dev

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true

    - name: Add musl target
      run: rustup target add x86_64-unknown-linux-musl

    - name: Update time crate
      run: cargo update -p time --precise 0.3.36

    - name: Build release static musl (only TLS, no gssapi)
      env:
        LIBCLANG_PATH: /usr/lib/llvm-14/lib
      run: |
        if [ ! -e /usr/lib/llvm-14/lib/libclang.so ]; then
          LIBCLANG_PATH=$(find /usr/lib/llvm-* -name libclang.so | head -n1 | xargs dirname)
          echo "Found libclang.so at: $LIBCLANG_PATH"
          export LIBCLANG_PATH
        fi
        cargo build --release --target x86_64-unknown-linux-musl --no-default-features --features nogssapi

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: rusthound-static-musl
        path: target/x86_64-unknown-linux-musl/release/rusthound
